"""baseline_schema

Revision ID: f8c485a61e10
Revises: 
Create Date: 2026-07-03 17:27:29.738848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c485a61e10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_cache', schema=None) as batch_op:
        batch_op.create_index('idx_ai_cache_task', ['task_type', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_cache_cache_key'), ['cache_key'], unique=True)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_path', sa.String(length=1024), nullable=True),
    sa.Column('resume_raw', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_normalized', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('domains_json', sa.Text(), nullable=True),
    sa.Column('strengths_json', sa.Text(), nullable=True),
    sa.Column('weaknesses_json', sa.Text(), nullable=True),
    sa.Column('recommended_roles_json', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=16), nullable=False),
    sa.Column('work_formats_json', sa.Text(), nullable=True),
    sa.Column('locations_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_path')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_short', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_company_source_external')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_companies_name', ['name'], unique=False)

    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.String(length=10), nullable=False),
    sa.Column('total_vacancies', sa.Integer(), nullable=True),
    sa.Column('new_7d', sa.Integer(), nullable=True),
    sa.Column('new_30d', sa.Integer(), nullable=True),
    sa.Column('fit_count', sa.Integer(), nullable=True),
    sa.Column('not_fit_count', sa.Integer(), nullable=True),
    sa.Column('avg_match_score', sa.Float(), nullable=True),
    sa.Column('median_salary_all', sa.Float(), nullable=True),
    sa.Column('median_salary_fit', sa.Float(), nullable=True),
    sa.Column('top_skills', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_full', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_remote_capital', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('idx_locations_city', ['city'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('is_hard_skill', sa.Boolean(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('idx_skills_category', ['category'], unique=False)

    op.create_table('search_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('desired_titles_json', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=16), nullable=False),
    sa.Column('keywords_include_json', sa.Text(), nullable=True),
    sa.Column('keywords_exclude_json', sa.Text(), nullable=True),
    sa.Column('required_skills_json', sa.Text(), nullable=True),
    sa.Column('experience_filter', sa.String(length=64), nullable=True),
    sa.Column('work_formats_json', sa.Text(), nullable=True),
    sa.Column('locations_json', sa.Text(), nullable=True),
    sa.Column('employment_types_json', sa.Text(), nullable=True),
    sa.Column('ai_suggestions_json', sa.Text(), nullable=True),
    sa.Column('hh_queries_json', sa.Text(), nullable=True),
    sa.Column('habr_queries_json', sa.Text(), nullable=True),
    sa.Column('geekjob_queries_json', sa.Text(), nullable=True),
    sa.Column('profile_label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('new_added', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('hh_found', sa.Integer(), nullable=False),
    sa.Column('habr_found', sa.Integer(), nullable=False),
    sa.Column('geekjob_found', sa.Integer(), nullable=False),
    sa.Column('search_settings_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['search_settings_id'], ['search_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index('idx_scan_runs_date', ['started_at'], unique=False)

    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('external_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_normalized', sa.String(length=512), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('description_full', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=16), nullable=False),
    sa.Column('salary_gross', sa.Boolean(), nullable=False),
    sa.Column('salary_text', sa.String(length=255), nullable=True),
    sa.Column('work_format', sa.String(length=32), nullable=True),
    sa.Column('work_format_raw', sa.String(length=128), nullable=True),
    sa.Column('schedule', sa.String(length=64), nullable=True),
    sa.Column('employment', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('experience_required', sa.String(length=64), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('experience_years_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('user_status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at_source', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('rule_score', sa.Integer(), nullable=False),
    sa.Column('rule_score_reasons', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('search_settings_id', sa.Integer(), nullable=True),
    sa.Column('profile_role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['search_settings_id'], ['search_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_url'),
    sa.UniqueConstraint('source', 'external_id', name='uq_vacancy_source_external')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index('idx_vacancies_format', ['work_format'], unique=False)
        batch_op.create_index('idx_vacancies_published', ['published_at'], unique=False)
        batch_op.create_index('idx_vacancies_salary', ['salary_from', 'salary_to'], unique=False)
        batch_op.create_index('idx_vacancies_status', ['status', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_profile_role'), ['profile_role'], unique=False)

    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.create_index('idx_ai_usage_created', ['created_at'], unique=False)

    op.create_table('vacancy_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_level', sa.String(length=16), nullable=False),
    sa.Column('matched_skills_json', sa.Text(), nullable=True),
    sa.Column('missing_skills_json', sa.Text(), nullable=True),
    sa.Column('strengths_for_vacancy_json', sa.Text(), nullable=True),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=32), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('cover_letter_draft', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'profile_id', 'match_level', name='uq_vacancy_match')
    )
    with op.batch_alter_table('vacancy_matches', schema=None) as batch_op:
        batch_op.create_index('idx_vacancy_matches_score', ['match_score'], unique=False)

    op.create_table('vacancy_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'skill_id', name='uq_vacancy_skill')
    )
    op.create_table('vacancy_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('tag_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'tag', 'tag_type', name='uq_vacancy_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_tags')
    op.drop_table('vacancy_skills')
    with op.batch_alter_table('vacancy_matches', schema=None) as batch_op:
        batch_op.drop_index('idx_vacancy_matches_score')

    op.drop_table('vacancy_matches')
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_usage_created')

    op.drop_table('ai_usage_log')
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_profile_role'))
        batch_op.drop_index('idx_vacancies_status')
        batch_op.drop_index('idx_vacancies_salary')
        batch_op.drop_index('idx_vacancies_published')
        batch_op.drop_index('idx_vacancies_format')

    op.drop_table('vacancies')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_scan_runs_date')

    op.drop_table('scan_runs')
    op.drop_table('search_settings')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('idx_skills_category')

    op.drop_table('skills')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('idx_locations_city')

    op.drop_table('locations')
    op.drop_table('daily_metrics')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('idx_companies_name')

    op.drop_table('companies')
    op.drop_table('candidate_profiles')
    with op.batch_alter_table('ai_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_cache_cache_key'))
        batch_op.drop_index('idx_ai_cache_task')

    op.drop_table('ai_cache')
    # ### end Alembic commands ###
